### PR TITLE
[WIP] Use craft runtime path for temp location

### PR DESCRIPTION
**Pull request by leevigraham**

### CODE REVIEW

**Comment by leevigraham** [comment]
@benjamminf Still working on this. Currently there is a response but it is:

> Error uploading the file: This file type is not allowed

**Comment by benjamminf** [comment]
Mate, thanks for your help with this! Wasn't aware of `getRuntimePath` - good to know. Might be a dumb question but have you made sure to allow `json` files in your config?

**Comment by leevigraham** [comment]
Ok last issue… CraftCMS v2.6.2945 doesn't include json as a valid upload filetype.

Adding the following to the general.php is a workaround:

`'extraAllowedFileExtensions' => 'json'`

**Comment by benjamminf** [comment]
Yeah that's expected, it's in the installation instructions ;) So has this solved your issue then?

**Comment by leevigraham** [comment]
@benjamminf Yep all good. No errors.

**Comment by leevigraham** [comment]
@klepl @pixeljitsu Does this merge solve https://github.com/benjamminf/craft-embedded-assets/issues/25

**Pull request merged**
